version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "${MONGO_HOST_PORT:-27017}:${MONGO_CONTAINER_PORT:-27017}"
    volumes:
      - mongoDB_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./BackEnd
    container_name: nest_backend
    restart: always
    env_file:
      - .env
    ports:
      - "${BACKEND_HOST_PORT:-3000}:3000"
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongoDB_data: